// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Google.SignIn;

namespace SignInExample
{
	public partial class ViewController : UIViewController
	{
		public ViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			signInButton.TouchUpInside += (_, __) => {
				SignIn.SharedInstance.SignInWithPresentingViewController (this, (result, error) => {
					if (error != null) {
						statusText.Text = error.LocalizedDescription;
						return;
					}

					var user = result?.User ?? SignIn.SharedInstance.CurrentUser;
					statusText.Text = user?.Profile?.Name != null
						? $"Signed in user: {user.Profile.Name}"
						: "Signed in";

					ToggleAuthUI ();
				});
			};

			// Automatically sign in the user.
			if (SignIn.SharedInstance.HasPreviousSignIn) {
				SignIn.SharedInstance.RestorePreviousSignInWithCompletion ((user, error) => {
					if (error != null) {
						statusText.Text = error.LocalizedDescription;
						return;
					}

					statusText.Text = user?.Profile?.Name != null
						? $"Signed in user: {user.Profile.Name}"
						: "Signed in";

					ToggleAuthUI ();
				});
			}

			ToggleAuthUI ();

			statusText.Text = "Google Sign in\niOS Demo";
		}

		partial void didTapSignOut (NSObject sender)
		{
			SignIn.SharedInstance.SignOutUser ();
			ToggleAuthUI ();
		}

		partial void didTapDisconnect (NSObject sender)
		{
			SignIn.SharedInstance.DisconnectWithCompletion (error => {
				if (error != null) {
					statusText.Text = error.LocalizedDescription;
					return;
				}

				statusText.Text = "Disconnected user";
				ToggleAuthUI ();
			});
		}

		void ToggleAuthUI ()
		{
			if (SignIn.SharedInstance.CurrentUser == null) {
				// Not signed in
				statusText.Text = "Google Sign in\niOS Demo";
				signInButton.Hidden = false;
				signOutButton.Hidden = true;
				disconnectButton.Hidden = true;
			} else {
				// Signed in
				var name = SignIn.SharedInstance.CurrentUser.Profile?.Name;
				statusText.Text = name != null ? $"Signed in user: {name}" : "Signed in";
				signInButton.Hidden = true;
				signOutButton.Hidden = false;
				disconnectButton.Hidden = false;
			}
		}

		public override UIStatusBarStyle PreferredStatusBarStyle ()
		{
			return UIStatusBarStyle.LightContent;
		}
	}
}
