variables:
  Codeql.Enabled: true
  Codeql.TSAEnabled: true
  Codeql.TSAOptionsPath: '.ci/tsaoptions.json'
  CodeQL.Cadence: 0 # Remove this variable when CodeQL is working ok. This is for testing only.
  timeoutInMinutes: 360
  continueOnError: 'true'
  poolName: 'Azure Pipelines'
  imageName: 'macOS-latest'
  verbosity: 'diagnostic'

resources:
  repositories:
    - repository: yaml-templates
      type: github
      name: xamarin/yaml-templates
      endpoint: xamarin
      ref: refs/heads/main

schedules:
  - cron: '0 12 * * 0'
    displayName: 'Weekly Compliance Check'
    branches:
      include: [ 'main' ]
    always: false

pool:
  name: $(poolName)
  vmImage: $(imageName)

steps:
    - checkout: self

    # Component Governance
    - template: security/component-governance/v0.yml@yaml-templates

    # CredScan
    - template: security/credscan/v3.yml@yaml-templates

    # PoliCheck
    - template: security/policheck/v2.yml@yaml-templates

    # Publish Report
    - template: security/publish-report/v2.yml@yaml-templates
