trigger:
  - main
  - refs/tags/*

resources:
  repositories:
    - repository: internal-templates
      type: github
      name: xamarin/yaml-templates
      endpoint: xamarin
      ref: refs/heads/main
    - repository: components
      type: github
      name: xamarin/XamarinComponents
      endpoint: xamarin

variables:
  BUILD_COMMIT: $(Build.SourceVersion)
  BUILD_NUMBER: $(Build.BuildNumber)

jobs:
  - template: .ci/build.yml@components
    parameters:
      timeoutInMinutes: 180
      areaPath: 'DevDiv\Xamarin SDK\iOS and Mac'
      cakeTarget: 'build'
      cakeExtraArgs: '--names=$(SdksNames)'
      windowsImage: ''
      xcode: '13.1'

  - ${{ if ne(variables['System.TeamProject'], 'devdiv') }}:
    - template: compliance/sbom/job.v1.yml@internal-templates
      parameters:
        artifactNames: ['nuget']
        packageName: 'Xamarin Google APIs Components for iOS'
        packageFilter: '*.nupkg'
        dependsOn: [ 'build' ]

  - ${{ if eq(variables['System.TeamProject'], 'devdiv') }}:
    - template: sign-artifacts/jobs/v2.yml@internal-templates
      parameters:
        dependsOn: [ 'build' ]
        condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')

    - template: compliance/sbom/job.v1.yml@internal-templates
      parameters:
        artifactNames: ['nuget-signed']
        packageName: 'Xamarin Google APIs Components for iOS'
        packageFilter: '*.nupkg'
        dependsOn: [ 'signing' ]
        condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
