<Project>
  <PropertyGroup>
    <_GoogleTagManagerAssemblyName>Google.TagManager, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null</_GoogleTagManagerAssemblyName>
    <_GoogleTagManagerItemsFolder>GTagM-9.2.0</_GoogleTagManagerItemsFolder>
    <_GoogleTagManagerSDKBaseFolder>$(XamarinBuildDownloadDir)$(_GoogleTagManagerItemsFolder)\</_GoogleTagManagerSDKBaseFolder>
    <_GoogleTagManageFrameworksBaseFolder>$(_GoogleTagManagerSDKBaseFolder)GoogleTagManager-9.2.0\Frameworks\</_GoogleTagManageFrameworksBaseFolder>
  </PropertyGroup>
  <!-- Framework names to strip bitcode -->
  <ItemGroup Condition="('$(OutputType)'!='Library' OR '$(IsAppExtension)'=='True')">
    <_FrameworkNamesToStripBitcode Include="GoogleTagManager" />
  </ItemGroup>
  <ItemGroup Condition="('$(OutputType)'!='Library' OR '$(IsAppExtension)'=='True')">
    <XamarinBuildDownload Include="$(_GoogleTagManagerItemsFolder)">
      <Url>https://dl.google.com/firebase/ios/tagmanager/17aa166d14dad8ed/GoogleTagManager-9.2.0.tar.gz</Url>
      <Kind>Tgz</Kind>
    </XamarinBuildDownload>
    <NativeReference Include="$(_GoogleTagManageFrameworksBaseFolder)GoogleTagManager.xcframework">
      <Kind>Framework</Kind>
      <SmartLink>True</SmartLink>
      <ForceLoad>True</ForceLoad>
      <LinkerFlags>-ObjC -lsqlite3 -lz</LinkerFlags>
      <Frameworks>AdSupport CoreTelephony JavaScriptCore SystemConfiguration UIKit</Frameworks>
    </NativeReference>
  </ItemGroup>
</Project>